### PR TITLE
Automated multiarch builds for docker

### PR DESCRIPTION
**Pull request by BlackDark**
#### Description

Automating docker builds for multi arch.
Tested resulting images for first test build on a MacBook Pro (amd64) and a RPi 3 (armv6?) and runs.
See here: https://hub.docker.com/repository/docker/blackdark93/glances/tags?page=1

Continous builds and pushes to DockerHub via Github actions.

Currently this is only a discussion point of how you like the changes. Will do a cleanup then.

#### Resume

* Bug fix: no
* New feature: no
* Fixed tickets: #1419,1479,1662

### CODE REVIEW

**Comment by nicolargo** [comment]
Hi @BlackDark 

look great !

Can you pull a new version with the needed cleanup ?

After the merge i will disable the old school way to build the Glances Docker images and use this one.

Nicolas

**Comment by BlackDark** [comment]
Hey @nicolargo 
sorry for the late actions. Have updated the code, rebased and squashed the commits.

Sum-up:
- Merged Dockerfiles into one. The DEV build decision happens in the dockerfile based on the version argument. See here: https://github.com/nicolargo/glances/pull/1716/files#diff-d5c33ce43596b52ba02ae29e8e1c4c71R26
- CI is building master, develop and tags starting with v*
- Following platforms will be build: linux/amd64,linux/arm/v7,linux/arm64,linux/386 (can be updated as required) https://github.com/nicolargo/glances/pull/1716/files#diff-90829e76e906f1c73140c7ded7e1b268R22
- you have to configure 3 secrets in github settings for the repo:
  - DOCKER_IMAGE (the repo name: nicolargo/glances)
  - DOCKER_USERNAME (https://github.com/nicolargo/glances/pull/1716/files#diff-90829e76e906f1c73140c7ded7e1b268R65)
  - DOCKER_PASSWORD (https://github.com/nicolargo/glances/pull/1716/files#diff-90829e76e906f1c73140c7ded7e1b268R66)

**Comment by nicolargo** [comment]
@BlackDark Just merged and configured ! 

I have disabled the autobuild in the Docker Hub configuration and let the Github action take over.

image

Thanks for this hard work !

**Comment by firefly2442** [comment]
Would it be possible to build them for the `latest` tag as well?

**Pull request merged**
