### PR TITLE
[Web UI] add ports plugin

### PR DESCRIPTION
**Pull request by nclsHart**
#### Description

ports

#### Resume

* Bug fix: no
* New feature: yes
* Fixed tickets: #734

### CODE REVIEW

**Comment by nclsHart** [comment]
@nicolargo It's strange, I get different results (very different) between values displayed by the curse and the web interface.

**Comment by nicolargo** [comment]
Strange... will have a look...

**Comment by nicolargo** [comment]
@nclsHart Do you have the same value when you only ran the Web UI ?

**Comment by nclsHart** [comment]
@nicolargo Values are always lower on web UI even with only one instance running at the same time.

**Pull request merged**
