### PR TITLE
Feature/angularjs

### PR DESCRIPTION
**Pull request by sylvainmouquet**
AngularJS first version (merged with the current develop branch)
The alert and sensors plugins are not been yet implemented but i prefer push a request for sharing the same base with others developers

### CODE REVIEW

**Comment by nicolargo** [comment]
Nice ! I will have a look this evening. Perhaps we can plan to integrate the feature in the next version (Glances 2.3).

**Comment by nicolargo** [comment]
I just create a feature branch: https://github.com/nicolargo/glances/tree/feature/issue480

Had to change this line and remove the encoding parameter:

https://github.com/nicolargo/glances/blob/feature/issue480/glances/outputs/glances_bottle.py#L277

I test this evening...

**Comment by nclsHart** [comment]
I've the same issue (Python 2.7.3) : 

```
File "glances/outputs/glances_bottle.py", line 250, in display
    f = open(path, encoding="utf-8")
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by desbma** [comment]
This is a Python 3 argument only and is the default anyway so you can safely remove it.

**Comment by nicolargo** [comment]
Please submit the pull request to the feature branch https://github.com/nicolargo/glances/tree/feature/issue480

**Comment by nicolargo** [comment]
Followed with https://github.com/nicolargo/glances/issues/473

**Pull request closed without merging**
