### PR TITLE
Reduced complexity of `glances.plugins.percpu.PluginModel.msg_curse()`

### PR DESCRIPTION
**Pull request by ariel-anieli**
#### Description

Part of #2801. Quick look:

20240724_20h15m07s_grim

No quick look:

20240724_20h15m22s_grim

Tests are all passing:

```shell
# bin/python unittest-core.py | grep -iP 'OK:fail'
.....................................
----------------------------------------------------------------------
Ran 37 tests in 13.136s

OK
```

#### Resume

Broken `msg_curse`: if no stats returns empty list, else:

1. `define_headers_from_os`
2. `maybe_build_string_msg`
3. `display_cpu_stats_per_line`
4. `manage_max_cpu_to_display`
5. Then, for CPU:
   * `display_cpu_header_in_columns`
   * `display_cpu_stats_in_columns`
6. Hence, `summarize_all_cpus_not_displayed`

### CODE REVIEW

**Comment by ariel-anieli** [comment]
Reverting the push; I introduced a mistake.

**Comment by ariel-anieli** [comment]
All good; the PR is ready.

**Comment by ariel-anieli** [comment]
I saw regression; I am working on it.

**Comment by ariel-anieli** [comment]
20240725_00h10m16s_grim

Fixed it: it was a misaligned statement

**Comment by ariel-anieli** [comment]
:slightly_smiling_face: It should be good now; the PR is ready.

**Comment by nicolargo** [comment]
Perfect ! merged into develop.

Great work @ariel-anieli !

**Pull request merged**
