### PR TITLE
[WIP] Add authentication to the Web server

### PR DESCRIPTION
**Pull request by notFloran**
Related to #446

Todo : 
Update doc

### CODE REVIEW

**Comment by nicolargo** [comment]
Works like a charm.

I just add the following message:

python -m glances -w --password
Define the password for the Glances web server
*User name: glances*
Password:

**Comment by HLFH** [comment]
Hi. I'm not sure if I understand. To start Glances, I'm using [this package (2.4.2-1)](https://www.archlinux.org/packages/community/any/glances/) + Nginx + this systemd file:
```bash
[Unit]
Description=Glances daemon
After=network.target

[Service]
ExecStartPre=/usr/bin/touch /tmp/glances.log
ExecStart=/usr/bin/glances -w
ExecStartPost=/usr/bin/chmod a+rw /tmp/glances.log

[Install]
WantedBy=multi-user.target
```
How could I add a username and a password? Should I get this line? ExecStart=/usr/bin/glances -w --password "password". I don't arrive to get it working.

**Comment by nicolargo** [comment]
The Web authentication will be available in the next release (2.5) and can be tested from the GIT develop branch.

Best way to process after downloaded the develop branch (https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version) is to run a first time glances with the -w --password options. A login/password will be prompted and save.

After that, just start Glances with  -w --password options, no more password will be asked when the server is started.

**Comment by HLFH** [comment]
@nicolargo Hi, it seems that there is [no more issues with the 2.5 release](https://github.com/nicolargo/glances/milestones/Version%202.5). Could you release it? So I could test Web authentication. Thanks!

**Comment by nicolargo** [comment]
The team is in validation (RC is available in the develop branch). If no bugs are found this week, i plan to release it next week.

Wait and see...

**Pull request merged**
