### PR TITLE
Fix Link address in Wiki page #2575

### PR DESCRIPTION
**Pull request by shubhalgupta**
#### Description

Please describe the goal of this pull request.

For any questions concerning installation or use, please open a discussion (https://github.com/nicolargo/glances/discussions), not an issue.

#### Resume

* Bug fix: yes
* New feature: no
* Fixed tickets: comma-separated list of tickets fixed by the PR, if any

### CODE REVIEW

**Comment by shubhalgupta** [comment]
@monochromec, we have to update README file right?

**Comment by monochromec** [comment]
IMHO Updating the wiki page as outlined in my comment should be sufficient. :-)

**Comment by shubhalgupta** [comment]
Can you please tell where is wiki page?

**Comment by monochromec** [comment]
@shubhalgupta Sorry, I should have been more precise in the original issue. The wiki URL in question is https://github.com/nicolargo/glances/wiki/How-to-create-a-new-plugin-%3F and the wrong link is "First of all, have a look [on existing plugins]_(http://glances.readthedocs.io/en/stable/aoa/index.html_) and ask you a simple question: is it possible to improve an existing plugin instead of create a new one".

**Pull request closed without merging**
