### PR TITLE
Update public ip at intervals

### LINKED ISSUE #2028: Update external IP address
At the top of the display where:

     **machine.name (openSUSE Tumbleweed 20220408 64bit / Linux 5.17.1-1-default) - IP 192.168.0.150/24 Pub 111.111.111.111**

is shown the Pub 111.111.111.111 is only refreshed when glances is loaded. If that IP where to change in the case of a VPN address the new address is never refreshed.

I was wondering if this might be something that could be looked into?

### PR DESCRIPTION
**Pull request by RazCrimson**
#### Description

Let the Public IP address get updated every `t` seconds

The time interval can be configured by the config option under `ip` section with `public_refresh_interval`.
Default value is 300 seconds.

#### Resume

* Bug fix: no
* New feature: no
* Fixed tickets: Closes #2028

### CODE REVIEW

**Comment by nicolargo** [comment]
Thanks for the PR @RazCrimson !

**Comment by vvstubbs** [comment]
Okay this is really dumb. I cleaned out all my old installs so to do a fresh install from the recent git pull from the repository and installed all is good redid the glances.conf file and the IP information is not displayed, I press the [ I ] key and nothing. In the conf file 
[ip]
disable=False
remind and old confused brain

**Comment by vvstubbs** [comment]
late breaking extra: But if I install as root IP works. as root of course installs in  /usr/bin/glances and uses the system python --version 3.8 and my user of course is local with my python --version 3.9, not a big deal but still odd to me

**Comment by vvstubbs** [comment]
I works perfectly

**Pull request merged**
