### PR TITLE
Fix warnings and improve Python 3.9 compatibility.

### PR DESCRIPTION
**Pull request by tirkarthi**
#### Description

Fixes below warnings using raw strings and !=. Fixes `isAlive` attribute error.

```
./glances/config.py:108: DeprecationWarning: invalid escape sequence \`
  self.re_pattern = re.compile('(\`.+?\`)')
./glances/outputs/glances_curses.py:700: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if p is not 'load':
./glances/amps/glances_systemd.py:20: DeprecationWarning: invalid escape sequence \/
  """
./glances/amps/glances_systemv.py:20: DeprecationWarning: invalid escape sequence \/
  """
./glances/amps/glances_nginx.py:20: DeprecationWarning: invalid escape sequence \/
  """
./glances/amps/glances_default.py:20: DeprecationWarning: invalid escape sequence \/
  """
```

#### Resume

* Bug fix: yes
* New feature: no
* Fixed tickets: #1585

### CODE REVIEW

**Comment by nicolargo** [comment]
Hi @tirkarthi,

did the second patch (commit 2e00997e3392fea60d5fc476dc3755c434301237) preserve the Python2 compatibility ?

Nicolas

**Comment by tirkarthi** [comment]
Yes, is_alive is present in Python 2 too : https://docs.python.org/2/library/threading.html#threading.Thread.is_alive

**Comment by nicolargo** [comment]
Ok perfect !
Thanks for the PR.

**Comment by nicolargo** [comment]
Ok perfect !
Thanks for the PR.

**Comment by nicolargo** [comment]
Ok perfect !
Thanks for the PR.

**Comment by nicolargo** [comment]
Ok perfect !
Thanks for the PR.

**Comment by vstinner** [comment]
> did the second patch (commit 2e00997) preserve the Python2 compatibility ?

The 2.7 job of Travis CI is green :-) (tests passed)

**Comment by nicolargo** [comment]
Will merge it as soon as possible.

Nicolas

**Comment by tirkarthi** [comment]
Thanks @vstinner  and @nclsHart for the review :)

**Pull request merged**
