### PR TITLE
RabbitMQ export

### PR DESCRIPTION
**Pull request by Katyucha**
RabbitMQ export for glances. Usefull for an ELK

### CODE REVIEW

**Comment by nicolargo** [comment]
Hi @Katyucha , thk for the pull request, it will be usefull for most users !

Some points to correct before the final pull request :)

* Python 3 compatibility is broken
* update documentation (docs/glances-doc.rst and man/glances.1)

**Comment by Katyucha** [comment]
Bon, bah , je m'y recolle
Ok, i'll make better :)

**Comment by asergi** [comment]
@Katyucha 
```python
try:
    from configparser import NoOptionError, NoSectionError
except ImportError:  # Python 2
    from ConfigParser import NoOptionError, NoSectionError
```

**Comment by Katyucha** [comment]
Thanks a lot ! I write the manpage and doc this evening and pull it !

**Comment by Katyucha** [comment]
Bon, ca compile bien en python 3.4 mais ca marche pas ...
So, compile is good on python 3.4 but not work

**Pull request closed without merging**
