### PR TITLE
[Web UI] dependency manager and build system

### PR DESCRIPTION
**Pull request by nclsHart**
#### Description

Aims of this pull request : 

1. Reduce initial request number drastically 
2. Be able to use a dependency manager for the js libs
3. Optimize assets with a build system

In resume : better perfs and maintenability.

I added a README in order to explain how to work on the Web UI from now. 

**Please, This PR needs tests.**

#### Resume

* Bug fix: no
* New feature: yes

### CODE REVIEW

**Comment by nicolargo** [comment]
Thanks @nclsHart . I am going to test it !

**Comment by nicolargo** [comment]
Hi @nclsHart ,

if i understant, to "build" the WebUI, i need to follow this procedure:

1. Go to the _glances/outputs/static_ folder
2. Run _npm install_ 
3. Run _npm run build_
4. Run _npm run watch_

That all !

Is it correct ?

Perhaps it will be great to have a Makefile to other script file to automatically done this and the documentation generation (what do you think @asergi) ?

**Comment by nicolargo** [comment]
Oopsss...

$ npm run build
=> OK

$ npm run build

> @ build /home/nicolargo/Dropbox/dev/glances/glances/outputs/static
> gulp build


/home/nicolargo/Dropbox/dev/glances/glances/outputs/static/node_modules/gulp-angular-templatecache/node_modules/jsesc/jsesc.js:3
const object = {};
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nicolargo/Dropbox/dev/glances/glances/outputs/static/node_modules/gulp-angular-templatecache/index.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by nclsHart** [comment]
@nicolargo You need to build the Web UI only during development. 

You don't need to run the build and the watch command, they are complementary : 

The build command builds all the assets and the watch command will watchs for changes during your development and rebuild only changed assets.

The built files are versionned to avoid the need to build during setup and a dependency on js tools. 

I could add commands to build assets in the makefile.

**Comment by nclsHart** [comment]
@nicolargo I added some complementary explanation in the README to explain the procedure.

What is your nodejs version?

**Comment by nicolargo** [comment]
0.10.25...

**Comment by nicolargo** [comment]
Ok, it is more clear for me.

The WebUI starts much faster !

Nice jobs !

**Comment by nicolargo** [comment]
What kind of test do you need ?

**Comment by nclsHart** [comment]
@nicolargo You seem to be on a maintenance release reaching his end of life. I think you'll need to upgrade your nodejs version to v4.x. 

I just wanted to be sure the Web UI is always working on another config and environment than mine.

**Comment by nicolargo** [comment]
Ok, but as i understand, it is not necessary to have the build environment on my side for the moment.

For the test, it works like a charm on my configuration (Ubuntu).

**Comment by nclsHart** [comment]
@nicolargo Yes you are right, you'll need it only if you want to work on the Web UI.

Ok, so I think this PR is ready to be merged :).

**Comment by nicolargo** [comment]
Done !

Great job. Thanks !

**Comment by nicolargo** [comment]
@nclsHart The PR looks to break the API,can you have a look ?

```
./unitest-restful.py 
RESTful API unitary tests for Glances 2.7_BETA

==============================================================================
INFO: [TEST_000] Start the Glances Web Server
Run the Glances Web Server on port 61234
Please wait 5 seconds...
Glances web server started on http://0.0.0.0:61234/
.
==============================================================================
INFO: [TEST_001] Get all stats
HTTP RESTful request: http://localhost:61234/api/2/all
.
==============================================================================
INFO: [TEST_002] Plugins list
HTTP RESTful request: http://localhost:61234/api/2/pluginslist
.
==============================================================================
INFO: [TEST_003] Plugins
HTTP RESTful request: http://localhost:61234/api/2/load
F
==============================================================================
INFO: [TEST_004] Items for the CPU method
E
==============================================================================
INFO: [TEST_005] Item=Value for the PROCESSLIST method
http://localhost:61234/api/2/processlist/pid/0
F
==============================================================================
INFO: [TEST_006] Get all limits
HTTP RESTful request: http://localhost:61234/api/2/all/limits
.
==============================================================================
INFO: [TEST_007] Get all views
HTTP RESTful request: http://localhost:61234/api/2/all/views
.
==============================================================================
INFO: [TEST_008] Plugins limits
HTTP RESTful request: http://localhost:61234/api/2/load/limits
F
==============================================================================
INFO: [TEST_009] Plugins views
HTTP RESTful request: http://localhost:61234/api/2/load/views
F
==============================================================================
INFO: [TEST_010] History
HTTP RESTful request: http://localhost:61234/api/2/cpu/history
E
==============================================================================
INFO: [TEST_999] Stop the Glances Web Server
Stop the Glances Web Server
.
======================================================================
ERROR: test_004_items (__main__.TestGlances)
Items.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitest-restful.py", line 110, in test_004_items
    for i in ilist.json():
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 2 column 5 (char 5)

======================================================================
ERROR: test_010_history (__main__.TestGlances)
History.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitest-restful.py", line 178, in test_010_history
    self.assertIsInstance(req.json(), dict)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 2 column 5 (char 5)

======================================================================
FAIL: test_003_plugins (__main__.TestGlances)
Plugins.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitest-restful.py", line 93, in test_003_plugins
    self.assertTrue(req.ok)
AssertionError: False is not true

======================================================================
FAIL: test_005_values (__main__.TestGlances)
Values.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitest-restful.py", line 125, in test_005_values
    self.assertTrue(req.ok)
AssertionError: False is not true

======================================================================
FAIL: test_008_plugins_limits (__main__.TestGlances)
Plugins limits.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitest-restful.py", line 157, in test_008_plugins_limits
    self.assertTrue(req.ok)
AssertionError: False is not true

======================================================================
FAIL: test_009_plugins_views (__main__.TestGlances)
Plugins views.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unitest-restful.py", line 169, in test_009_plugins_views
    self.assertTrue(req.ok)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 12 tests in 6.645s

FAILED (failures=4, errors=2)
```

**Comment by nicolargo** [comment]
@nclsHart Nervermind, i correct the issue...

**Comment by nclsHart** [comment]
@nicolargo Ok, thanks.

**Pull request merged**
