### PR TITLE
Refactored `glances.globals.pretty_date()`, version 2

### PR DESCRIPTION
**Pull request by ariel-anieli**
#### Description

* refactored `glances.globals.pretty_date()`, version 2
* all tests are passing:
```shell
# make test 2>&1 | grep -Pi '^ok|^fail'
OK
OK
OK
```

#### Resume

* part of #2801
* follows from f6279baacd4cf0b27ca10df6dc01f091ea86a40a; which caused #2973.

### CODE REVIEW

**Comment by ariel-anieli** [comment]
Work in progress.

**Comment by ariel-anieli** [comment]
Ready to go.

**Comment by ariel-anieli** [comment]
Working on it; some tests are failing.

**Comment by ariel-anieli** [comment]
Ready to go; all tests are passing on CI/CD.

**Comment by nicolargo** [comment]
Thanks @ariel-anieli  !

Merged into develop branch

**Pull request merged**
