### PR TITLE
Updated WebUI dependencies

### LINKED ISSUE #2389: WebUI build failed with VueJS >= 3.3.0
After merging the PR https://github.com/nicolargo/glances/pull/2388 Glances WebUI failed to build:

```
> build
> webpack --progress --mode=production

[webpack-cli] Failed to load '/home/nicolargo/dev/glances/glances/outputs/static/webpack.config.js' config
[webpack-cli] Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
make: *** [Makefile:117: webui] Error 2
```

Problem is reproduced with all VueJS version >= 3.3.0. 

Downgraded to VueJS version 3.2.47 solves the issue.

```
package.json:        "vue": "^3.2.47"
```

### PR DESCRIPTION
**Pull request by fr4nc0is**
Fix #2389

### CODE REVIEW

**Comment by fr4nc0is** [comment]
Maybe I've read too fast.
Maybe not a problem from dependencies.
The error stack refers to `@vitejs/plugin-vue`.
Did you try to install the plugin ? Your local package.json/package-lock.json differs from the one provided in the `develop` branch ?

**Comment by nicolargo** [comment]
Nope i just run "make webui" from the develop branch and from your branch.

Did not try to install @vitejs/plugin-vue plugin... How to include it in the package.json ?

**Comment by fr4nc0is** [comment]
Didn't found any references

```
$ grep -rnw './glances/outputs/static/' -e 'plugin-vue' --exclude-dir=node_modules
./glances/outputs/static/package.json:16:        "eslint-plugin-vue": "^9.12.0",
./glances/outputs/static/package-lock.json:20:                "eslint-plugin-vue": "^9.12.0",
./glances/outputs/static/package-lock.json:2658:        "node_modules/eslint-plugin-vue": {
./glances/outputs/static/package-lock.json:2660:            "resolved": "https://registry.npmjs.org/eslint-plugin-vue/-/eslint-plugin-vue-9.12.0.tgz",
./glances/outputs/static/package-lock.json:10274:        "eslint-plugin-vue": {
./glances/outputs/static/package-lock.json:10276:            "resolved": "https://registry.npmjs.org/eslint-plugin-vue/-/eslint-plugin-vue-9.12.0.tgz",
```

Can you try resetting package.json/package-lock.json/node_modules files/folders ?

**Comment by nicolargo** [comment]
Same issue:

```
npm run build

> build
> webpack --progress --mode=production

[webpack-cli] Failed to load '/home/nicolargo/dev/glances/glances/outputs/static/webpack.config.js' config
[webpack-cli] Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

after a clean of the following file/folder:

```
rm package-lock.json
rm -rf package-lock.json
```

PS: i did not clean/rm the package.json file because i can not run the npm install anymore without this file...

**Comment by nicolargo** [comment]
No problem on the develop branch.

**Comment by fr4nc0is** [comment]
@nicolargo,

Can you give a new try ?
Hope this fix the dependencies issue
The branch was updated w/ `force` option

**Comment by nicolargo** [comment]
Not better....

```
# rm -rf node_modules/ 
# rm package-lock.json

``
# npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'copy-webpack-plugin@11.0.0',
npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'del@7.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-vue@9.12.0',
npm WARN EBADENGINE   required: { node: '^14.17.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'less-loader@11.1.0',
npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sass@1.62.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sass-loader@13.2.2',
npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'webpack-cli@5.1.1',
npm WARN EBADENGINE   required: { node: '>=14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vue-eslint-parser@9.3.0',
npm WARN EBADENGINE   required: { node: '^14.17.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@webpack-cli/configtest@2.1.0',
npm WARN EBADENGINE   required: { node: '>=14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@webpack-cli/info@2.0.1',
npm WARN EBADENGINE   required: { node: '>=14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@webpack-cli/serve@2.0.4',
npm WARN EBADENGINE   required: { node: '>=14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'commander@10.0.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '8.19.2' }
npm WARN EBADENGINE }

added 497 packages, and audited 498 packages in 20s

95 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
# npm run build

> build
> webpack --progress --mode=production

[webpack-cli] Failed to load '/home/nicolargo/dev/glances/glances/outputs/static/webpack.config.js' config
[webpack-cli] Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nicolargo/dev/glances/glances/outputs/static/node_modules/vue-loader/dist/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by fr4nc0is** [comment]
I don't understand what is happening.
The missing package is explicity required as dev dependencies.
The errors mentionned during npm install show a version of nodejs (v12) < version required (v14)

**Comment by nicolargo** [comment]
How do i upgrade node js ?

I try `sudo npm install n -g` but the version is current: { node: `'v12.22.12`', npm: '8.19.2' }....

**Comment by fr4nc0is** [comment]
npm is related to nodejs
nodejs is related to the OS

On ubuntu Ubuntu 22.04.2 LTS, i'm currently running 16.20.0

```
$ node --version
v16.20.0
```

**Comment by nicolargo** [comment]
On my side Ubuntu 22.04 (upgraded from 20.04):

```
node --version
v12.22.12
```

I probably should upgrade it...

**Pull request merged**
