### PR TITLE
Fixed typos, refactored  `glances.plugins.ports.PluginModel.msg_curse()`

### PR DESCRIPTION
**Pull request by ariel-anieli**
#### Description

Fixed typos, refactored  [`glances.plugins.ports.PluginModel.msg_curse()`](https://scrutinizer-ci.com/g/nicolargo/glances/code-structure/develop/py-function/glances.plugins.ports.PluginModel.msg_curse)

#### Resume
Part of #2801.

### CODE REVIEW

**Comment by ariel-anieli** [comment]
Work in progress; spotted an error.

**Comment by ariel-anieli** [comment]
The PR is ready to go: the error was, in `build_str`: if `host`, the helper is `get_ports_alert`. With `url`, it is `get_web_alert`.

**Comment by nicolargo** [comment]
Thanks @ariel-anieli 

I will test it.

**Comment by ariel-anieli** [comment]
> Thanks @ariel-anieli
> 
> I will test it.

Your welcome, @nicolargo. Let me know if any regression happen.

**Comment by ariel-anieli** [comment]
@nicolargo, #2959 is a sequel of this PR: `get_web_alert` & `get_ports_alert` were refactored. I realized they shared the same logic.

**Pull request merged**
