### PR TITLE
Fix Docker ARM build

### LINKED ISSUE #1320: Docker image for ARM architecture
#### Description

For an enhancement or new feature: it would be cool if there were a docker image for ARM, or if your existing image were multi-arch like portainer.

### PR DESCRIPTION
**Pull request by cricket007**
#### Description

Fixes #1320 

Tested on Rock64 board

#### Resume

 - [x] Bug fix
* Fixed tickets: #1320

### CODE REVIEW

**Comment by nicolargo** [comment]
Thanks @cricket007 !

**Comment by nemchik** [comment]
Just to confirm is this now on docker hub at https://hub.docker.com/r/nicolargo/glances/ ? Is there a tag that can be pulled and will work?

**Comment by cricket007** [comment]
@nemchik If you look at the tags on Docker Hub, you can see `latest-arm`

**Comment by nemchik** [comment]
Seems to not be working for the user testing ARM for me
```
standard_init_linux.go:190: exec user process caused "exec format error"
Pulled correct
"Status: Downloaded newer image for nicolargo/glances:latest-arm
"
```

**Comment by cricket007** [comment]
What are you trying to run the container on? It worked fine on my `armv8` / `arm64` board. 

Though, I did build locally, rather than pull whatever is on DockerHub.

**Comment by nemchik** [comment]
I believe it was a raspberry pi (armhf)

**Comment by cricket007** [comment]
I believe there is a difference between armv7 / armhf and armv8 / arm64...

This PR was primarily to fix the failing builds on DockerHub

**Comment by cricket007** [comment]
I don't know about the previous `easypi` images, but the Python images support these architectures. 

https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by medelay** [comment]
Im still looking for a solution for this problem. I cant get it to run on my raspberry pi 4. I think it should be in armhf. a 64 bit wont run on it.

**Pull request merged**
