### PR TITLE
Migrate from gulp & bower to webpack & yarn

### PR DESCRIPTION
**Pull request by spike008t**
#### Description

Move out from `gulp` & `bower` and use `webpack` & `yarn`. `yarn` is not mandatory, we can use `npm` to build.

I did not update any vendor at the moment, I'll send an other PR with up to date vendors. 

Edit: I use latest nodejs lts version (eg: `v8.9.4` at the moment)

#### Resume

* Bug fix: no
* New feature: no
* Fixed tickets: #1234

### CODE REVIEW

**Comment by nicolargo** [comment]
@notFloran Can you have a look on this PR ?
@spike008t Thanks for your huge contribution !

**Comment by spike008t** [comment]
@nicolargo Oh! I'm gonna give a look, i'll update

**Comment by spike008t** [comment]
I've added the public folder as ignored. Could you try to exec `npm run build` from the `glances/output/static` folder before to run? I can remove the .gitignore and ship the glances.js

**Comment by nicolargo** [comment]
Can you make a new PR because this one has been closed (my fault, i have made a merge/revert).

**Comment by spike008t** [comment]
Yep no problem, should I add the public folder generated by webpack?

**Comment by nicolargo** [comment]
I realy don't know...

**Comment by spike008t** [comment]
ok, I'll add it for the moment

**Pull request merged**
