### PR TITLE
WebUI now take account of --fahrenheit option

### PR DESCRIPTION
**Pull request by notFloran**
#### Description

The fahrenheit option is now take account in the WebUI.

#### Resume

* Bug fix: yes
* New feature: no
* Fixed tickets: #1200

### CODE REVIEW

**Comment by notFloran** [comment]
@nicolargo Can you try it ? I'm on mac so no sensors

**Comment by nicolargo** [comment]
Almost perfect but...

selection_350

**Comment by notFloran** [comment]
@nicolargo Can you retry ?

**Comment by nicolargo** [comment]
Same issue with the commit be80ea286b9a4375ce105ea8088d7d412f59b89f ... :(

selection_352

**Comment by notFloran** [comment]
Sorry I forgot to build the webui ...

**Comment by nicolargo** [comment]
Perfect !

selection_353

I merge it.

Thanks :)

**Pull request merged**
