### PR TITLE
Refactorized `glances.plugins.containers.PluginModel.msg_curse()`

### PR DESCRIPTION
**Pull request by ariel-anieli**
#### Description

- part of #2801: this one might be cumbersome to review, I changed a lot of lines
- tests are all passing; user experience is the same (see screenshot: top, after changes; down, version 4.1.2)
- I don't have containers in local; it would be helpful to test with a machine that has containers.

Screenshot from 2024-08-12 23-36-22

#### Resume

Broken down in:

* `build_tile`
* `build_header`
* on each container, `build_data_line` calls `build_container_data`.

`build_container_data` does for a container:

* `maybe_add_engine_name_or_pod_name`
* `build_container_name`
* `build_status_name`
* `build_uptime_line`
* `build_cpu_line`
* `build_memory_line`
* `build_io_line`
* `build_net_line`
* `build_cmd_line`.

### CODE REVIEW

**Comment by ariel-anieli** [comment]
Work in progress.

**Comment by ariel-anieli** [comment]
The PR is ready.

**Comment by nicolargo** [comment]
Hi @ariel-anieli 

there is a little issue in the network rx/tx display:

image

**Comment by ariel-anieli** [comment]
> Hi @ariel-anieli
> 
> there is a little issue in the network tx display:
> 
> image
> 
> Previous version:
> 
> image

Thanks for the feedback, @nicolargo; could have another check? The function didn't add the message:
```shell
# git add -p glances/plugins/containers/__init__.py
diff --git a/glances/plugins/containers/__init__.py b/glances/plugins/containers/__init__.py
index 4b3ed698..7382b992 100644
--- a/glances/plugins/containers/__init__.py
+++ b/glances/plugins/containers/__init__.py
@@ -445,6 +445,7 @@ class PluginModel(GlancesPluginModel):
                 msg = f' {value:<7}'
             except (KeyError, TypeError):
                 msg = ' {:<7}'.format('_')
+            ret.append(self.curse_add_line(msg))
 
             return ret
```

**Comment by ariel-anieli** [comment]
That was a rebase.

**Comment by nicolargo** [comment]
Perfect @ariel-anieli 

merged into develop !

**Pull request merged**
