### PR TITLE
Fix #546

### LINKED ISSUE #546: Binary highlighting in TASKS-list is incorrect when path contains whitespaces
On OSX the green highlighting of the binary in the task list does not properly handle white spaces in the path e.g.

> /Applications/**Google** Chrome.app/Contents/MacOS/Google Chrome

expected behaviour would be

> /Applications/Google Chrome.app/Contents/MacOS/**Google Chrome**

(bold should be highlighted)

it's really not high priority just something I noticed.

### PR DESCRIPTION
**Pull request by desbma**
To test, run in a Bash shell (Linux):

    echo "void main() { pause(); }" > /tmp/s.c
    gcc /tmp/s.c -o '/tmp/a b'
    '/tmp/a b' a b c d &

Then start glances, you should see '/tmp/**a b** a b c d' in process list.

### CODE REVIEW

**Comment by nicolargo** [comment]
Tested and approved !
Thanks @desbma

**Comment by asergi** [comment]
I got several regressions after applying this patch. Here's some examles:
- `-zsh` -> `zsh`: the leading dash is stripped (wrong); the process is not even highlighted
- `/bin/sh /usr/bin/startx` -> `startx`
- `/bin/sh -c i3bar --bar_id=bar-0 --socket="/tmp/1000-runtime-dir/i3/ipc-socket.1098"` -> `sh`
- some long command lines are displayed correctly while others aren't:

Before: long-cmd-before
After: long-cmd-after

**Comment by nicolargo** [comment]
Mmmhhh...  Can you revert the merge? I am far away from computer today.

**Comment by desbma** [comment]
Since it's in the develop branch, I think we should fix remaining issues instead of reverting.
I'll have a look at @asergi's regressions today.

**Comment by nicolargo** [comment]
Ok @desbma

**Pull request merged**
