### PR TITLE
Plugin fs - cleaner impl to avoid duplicate entries when allow is set

### PR DESCRIPTION
**Pull request by RazCrimson**
Already fixed in 09c66999
A cleaner implementation of the fix..
In this case, I think fixing the cause of the bug is better than adding a cleanup at the end.

@nicolargo 
What do you suggest when looking at PRs from contributers (like #2299), 
Should I request for cleaner changes in cases where their fix works but could think of a better alternative/solution?
Or should I accept the changes and make the fix cleaner later when possible?  

What are your thoughts on this?

### CODE REVIEW

**Comment by nicolargo** [comment]
Top !

Thanks @RazCrimson !

**Comment by nicolargo** [comment]
For a minor change, it is better to accept the changes and make the fix cleaner later when possible...

For a big PR, you can ask to the contributor to rework.

**Comment by rhoriguchi** [comment]
thx @RazCrimson

**Comment by RazCrimson** [comment]
> thx @RazCrimson 

@rhoriguchi 
Sorry about the comments on the issue. 

I'm new to reviewing PRs here. 😅

If you are interested in contributing more, feel free to take a look at other open issues.

**Pull request merged**
